Magma (+CHIMP) notebook to find curves whose Jacobians are isogeny factors of the Jacobians of modular curves.
Via the period matrix, for now only for genus 2 curves where we have RM.

Example 2:
https://www.lmfdb.org/ModularForm/GL2/Q/holomorphic/23/2/a/a/
should give
https://www.lmfdb.org/Genus2Curve/Q/529/a/529/1
or something isogenous

## J_0(23)

In [1]:
X  := JZero(23);
X;

Modular abelian variety JZero(23) of dimension 2 and level 23 over Q


In [2]:
prec := 80;
SetDefaultRealFieldPrecision(prec);
C:=ComplexFieldExtra(prec);
Q:=RationalsExtra(prec);
Pi := Matrix(Periods(X, 10000)); // no control over precision really, instead use Eran's code
print Parent(Pi);
Pi := Transpose(ChangeRing(Pi, C));
g := #Rows(Pi);
P1 := Submatrix(Pi,1,1,g,g);
P2 := Submatrix(Pi,1,g+1,g,g);
Pi = HorizontalJoin(P2,P1);

Full KMatrixSpace of 4 by 2 matrices over C
[0.59153223605591049412844857456813206387023215502104975359443796091010267748572893 - 1.6874592734680125399313535764556124833596758476471892852623068887203284395879924*C.1 -0.59153223605591049412844857456813206387023215502104975359443796091010267748572893 - 1.6874592734680125399313535764556124833596758476471892852623068887203284395879924*C.1 -1.3543385605139576628095288989023432177531386555833329556794417959366338520677597 - 1.0837716284893304295801997816494484515107861906527159591608828822124678802648372*C.1 -1.5256126489160943373621606486684223077658130011245664041700076700530623491640616]
[0.76280632445804716868108032433421115388290650056228320208500383502653117458203096 - 0.60368764497868211035115379480616403184888965699447332610142400650786055932315512*C.1 -0.76280632445804716868108032433421115388290650056228320208500383502653117458203096 - 0.60368764497868211035115379480616403184888965699447332610142400650786055932315512*C.1 -0.59153223

In [3]:
_,pol := SomePrincipalPolarization(Pi); pol;

[ 0  0  0  1]
[ 0  0  1  1]
[ 0 -1  0  2]
[-1 -1 -2  0]


In [4]:
E, F := FrobeniusFormAlternating(Matrix(Integers(),pol)); E,F;

[ 0  0  1  0]
[ 0  0  0  1]
[-1  0  0  0]
[ 0 -1  0  0]

[ 1  0  0  0]
[-1  1  0  0]
[ 0  0  0  1]
[-2  0  1  0]


In [5]:
ReconstructCurve(Pi*Transpose(ChangeRing(F, C)), Q);

Hyperelliptic Curve defined by y^2 = -19/4*x^6 + 65/2*x^5 - 275/4*x^4 + 143/2*x^3 - 83/2*x^2 + 13*x - 7/4 over Rational Field
Mapping from: FldRat: Q to FldRat: Q
true


In [6]:
H:=$1;
Conductor(H);

529


In [8]:
R<x> := PolynomialRing(Rationals()); C := HyperellipticCurve(R![0, 0, 0, 0, 0, -1], R![1, 1, 0, 1]);
IsIsomorphic(C, H);

false


In [9]:
G2Invariants(C);
G2Invariants(H);

[ -1804229351/529, -39370210/529, 3145584/529 ]
[ -59797108943/148035889, 777839062/6436343, -9815520/279841 ]


In [10]:
IsIsogenousPeriodMatrices(PeriodMatrix(C), PeriodMatrix(H));

true 
[-2  0 -1  1]
[ 2 -1 -1  1]
[ 2 -3 -2  1]
[ 1 -1  1  0]

[1.828779826051639971545253677288545535123055991716477857944201349164212217450781113080716834976275247E-99 - 1.000113967371990609438810604767173339520421245469948828563235112824178556418395921216017019127650526E-99*$.1 -1.000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000006 - 5.998451406983345463308223426360256168061097961111054692744224884282517368518370179257673505348207507E-100*$.1]
[1.000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000003 - 4.496048058676761355825367316966712289719036581197493171264186422383695563898770949395219367239036070E-100*$.1 -2.928905190160829641927945342532436208595519361733421569363759973270808629511016626418335556016690826E-99 - 8.000911738975924875510484838137386716163369963759590628505880902593428451347167369728136153021204208E-100*$.1]


In [11]:
_,B,E:=IsIsogenousPeriodMatrices(PeriodMatrix(C), PeriodMatrix(H));

In [12]:
Determinant(B);

11


In [13]:
IsIsomorphicBigPeriodMatrices(PeriodMatrix(C), PeriodMatrix(H));

false 
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]

[0.0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 0.0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000]
[0.0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 0.0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000]


In [14]:
Factorization(Integers()!Discriminant(H));

[ <23, 6> ]


In [15]:
Factorization(Integers()!Discriminant(C));

[ <23, 2> ]


# Button time:

In [1]:
function GetCurve(N)
    Hs := [];
    for A in Decomposition(JZero(N)) do
        if Dimension(A) ne 2 then continue; end if;
        print A;
        prec := 80;
        SetDefaultRealFieldPrecision(prec);
        C:=ComplexFieldExtra(prec);
        Q:=RationalsExtra(prec);
        Pi := Matrix(Periods(A, 10000)); // no control over precision really, instead use Eran's code
        print "Periods computed";
        // Change convention
        Pi := Transpose(ChangeRing(Pi, C));
        g := #Rows(Pi);
        P1 := Submatrix(Pi,1,1,g,g);
        P2 := Submatrix(Pi,1,g+1,g,g);
        Pi = HorizontalJoin(P2,P1);
        _, pol := SomePrincipalPolarization(Pi); pol;
        print "Principal polarization found";
        E, F := FrobeniusFormAlternating(Matrix(Integers(), pol)); E,F;
        H := ReconstructCurve(Pi*Transpose(ChangeRing(F, C)), Q);
        // TODO can we twist it, yes we can
        print "Curve found";
        print H;
        Append(~Hs, H);
    end for;
    return Hs;
end function;

In [2]:
SetVerbose("CurveRec",2);

In [17]:
GetCurve(23);

Modular abelian variety JZero(23) of dimension 2 and level 23 over Q
Periods computed
[0.59153223605591049412844857456813206387023215502104975359443796091010267748572911 - 1.6874592734680125399313535764556124833596758476471892852623068887203284395879923*I -0.59153223605591049412844857456813206387023215502104975359443796091010267748572911 - 1.6874592734680125399313535764556124833596758476471892852623068887203284395879923*I -1.3543385605139576628095288989023432177531386555833329556794417959366338520677594 - 1.0837716284893304295801997816494484515107861906527159591608828822124678802648372*I -1.5256126489160943373621606486684223077658130011245664041700076700530623491640606]
[0.76280632445804716868108032433421115388290650056228320208500383502653117458203078 - 0.60368764497868211035115379480616403184888965699447332610142400650786055932315493*I -0.76280632445804716868108032433421115388290650056228320208500383502653117458203078 - 0.60368764497868211035115379480616403184888965699447332610142400

In [1]:
for N in [23,29,31,35,39,43,51,55] do
  print N;
  GetCurve(N);
end for;


>>   GetCurve(N);
     ^
User error: Identifier 'GetCurve' has not been declared or assigned


In [20]:
GetCurve(31);

Modular abelian variety JZero(31) of dimension 2 and level 31 over Q
Periods computed
[-0.25655036936015153745832296033861323428313181609194429941647634781274790392434267 - 1.1714841244880598206273447539570668483414813402875243650540357340737011382235563*I -0.67414756541403061635405536527069083259488805963099862373196577348134018779676010 - 1.7291583732029589894305762888156166618026060718043778091564038683160744408709616*I -1.3482951308280612327081107305413816651897761192619972474639315469626803755935202 -1.8613958695483643076247566512186081337560397514458858462968842425881761834422055]
[0.67414756541403061635405536527069083259488805963099862373196577348134018779676000 + 1.7291583732029589894305762888156166618026060718043778091564038683160744408709617*I -0.41759719605387907889573240493207759831175624353905432431548942566859228387241792 - 0.55767424871489916880323153485854981346112473151685344410236813424237330264740517*I -0.83519439210775815779146480986415519662351248707810864863097885

In [21]:
H31 := $1;

In [22]:
Discriminant(H31);

923521


In [23]:
R<x> := PolynomialRing(Rationals()); C31 := HyperellipticCurve(R![-3, -2, 3, 4, -5], R![1, 0, 1, 1]);
IsIsomorphicBigPeriodMatrices(PeriodMatrix(C31), PeriodMatrix(H31));

true 
[-1  0  1  0]
[ 0 -1  0  0]
[ 0  0 -1  0]
[ 0  0  0 -1]

[-1.000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 -1.428734239102843727769729435381676199314887493528498326518907304034540794883422744594310027325215037E-101*$.1]
[-2.000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 + 7.858038315065640502733511894599219096231881214406740795853990172189974371858825095268705150288682704E-101*$.1 1.000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 - 5.714936956411374911078917741526704797259549974113993306075629216138163179533690978377240109300860148E-101*$.1]


In [34]:
GetCurve(35);

Modular abelian variety 35B of dimension 2, level 5*7 and conductor 5^2*7^2 over Q
Periods computed
[2.0344845156385959587189816046261414363352354842742126496144678589164768743131624 + 3.4297156012533748377208689741567976283361400315957379944250789178846292769250282*I 3.4297156012533748377208689741567976283361400315957379944250789178846292769250282*I 0.34137737790521970185855171439075200617921139250668418599842392117685468822211667 + 2.7967836865569805000651056664007522880276526219964776184225553808924634644585069*I -1.6931071377333762568604298902353894301560240917675284636160439377396221860910457 + 0.63293191469639433765576330775604534030848740959926037600252353699216581246652131*I]
[1.3551746977763371181099603462742300741618209169523173942116389335989303116238128 - 0.22449698561694937177445393578315406677554759829967412260374619247899150676473582*I -0.22449698561694937177445393578315406677554759829967412260374619247899150676473582*I 1.6931071377333762568604298902353894301560240917675

In [35]:
H35 := $1[1];

In [40]:
print Discriminant(H35);
print Conductor(H35);

-52521875/1024
1225


In [39]:
R<x> := PolynomialRing(Rationals()); C35 := HyperellipticCurve(R![2, 1, 1, 2], R![0, 0, 1, 1]);
_, B, E := IsIsogenousPeriodMatrices(PeriodMatrix(C35), PeriodMatrix(H35));
Determinant(B);

4


In [41]:
GetCurve(39);

Modular abelian variety 39B of dimension 2, level 3*13 and conductor 3^2*13^2 over Q
Periods computed
[-1.9479957727195430887104091534008201605385193314059003365302071512467692042689652 + 3.2850353304939402127150869938619129658153557140463096967553528860290365581524110*I -2.1381363490931733820682900560011367073668748864781633554110761786565589888298268 + 2.6189598960494736394824076964965531813842451286522630532919517922715824580998191*I -2.1381363490931733820682900560011367073668748864781633554110761786565589888298268 + 0.66607543444446657323267929736535978443111058539404664346340109375745410005259195*I 1.3321508688889331464653585947307195688622211707880932869268021875149082001051839*I]
[-2.3282769254668036754261709586014532541952304415504263742919452060663487733906897 + 1.9528844616050070662497283991311933969531345432582164098285506985141283580472269*I 0.19014057637363029335788090260031654682835555507226301888086902740978978456086153 + 0.66607543444446657323267929736535978443111058539

In [42]:
H39 := $1[1];

In [44]:
print Discriminant(H39);
print Conductor(H39);

-4804839/1024
1521


In [47]:
R<x> := PolynomialRing(Rationals()); C39 := HyperellipticCurve(R![2, 3, 4, 1, 1], R![1, 0, 0, 1]);
_, B, E := IsIsogenousPeriodMatrices(PeriodMatrix(C39), PeriodMatrix(H39));
print Determinant(B);
IsIsomorphicBigPeriodMatrices(PeriodMatrix(C39), PeriodMatrix(H39));

2
false 
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]

[0.0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 0.0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000]
[0.0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 0.0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000]


# 29

In [4]:
GetCurve(29);

Modular abelian variety 29A of dimension 2, level 29 and conductor 29^2 over Q
Periods computed
[-0.37654698724107982110198349672387118556352867851261276291164560608602746481049411 - 1.8013180138484217343811640890994647590687462484108594261459528492849284189084255*I -0.75309397448215964220396699344774237112705735702522552582329121217205492962098823 -1.2674667407397804936201219032113335846470358605888944793017616699373513186293437 - 1.1808874900527529913958134087839717838526979128417611497003284332282471408594111*I -1.7818395069974013450362768129749247981670143641525634327802321277026477076376991]
[-0.51437276625762085141615490976359121351997850356366895347847045776529638900835601 - 1.1808874900527529913958134087839717838526979128417611497003284332282471408594111*I -1.0287455325152417028323098195271824270399570071273379069569409155305927780167120 -0.37654698724107982110198349672387118556352867851261276291164560608602746481049348 + 0.560456966257084248410462728468478808636649577272662873