Magma (+CHIMP) notebook to find curves whose Jacobians are isogeny factors of the Jacobians of modular curves.
Via the period matrix, for now only for genus 2 curves where we have RM.

Example 2:
https://www.lmfdb.org/ModularForm/GL2/Q/holomorphic/23/2/a/a/
should give
https://www.lmfdb.org/Genus2Curve/Q/529/a/529/1
or something isogenous

## J_0(23)

In [1]:
X  := JZero(23);
X;

Modular abelian variety JZero(23) of dimension 2 and level 23 over Q


In [2]:
prec := 80;
SetDefaultRealFieldPrecision(prec);
C:=ComplexFieldExtra(prec);
Q:=RationalsExtra(prec);
Pi := Matrix(Periods(X, 10000)); // no control over precision really, instead use Eran's code
print Parent(Pi);
Pi := Transpose(ChangeRing(Pi, C));
g := #Rows(Pi);
P1 := Submatrix(Pi,1,1,g,g);
P2 := Submatrix(Pi,1,g+1,g,g);
Pi = HorizontalJoin(P2,P1);

Full KMatrixSpace of 4 by 2 matrices over C
[0.59153223605591049412844857456813206387023215502104975359443796091010267748572893 - 1.6874592734680125399313535764556124833596758476471892852623068887203284395879924*C.1 -0.59153223605591049412844857456813206387023215502104975359443796091010267748572893 - 1.6874592734680125399313535764556124833596758476471892852623068887203284395879924*C.1 -1.3543385605139576628095288989023432177531386555833329556794417959366338520677597 - 1.0837716284893304295801997816494484515107861906527159591608828822124678802648372*C.1 -1.5256126489160943373621606486684223077658130011245664041700076700530623491640616]
[0.76280632445804716868108032433421115388290650056228320208500383502653117458203096 - 0.60368764497868211035115379480616403184888965699447332610142400650786055932315512*C.1 -0.76280632445804716868108032433421115388290650056228320208500383502653117458203096 - 0.60368764497868211035115379480616403184888965699447332610142400650786055932315512*C.1 -0.59153223

In [3]:
_,pol := SomePrincipalPolarization(Pi); pol;

[ 0  0  0  1]
[ 0  0  1  1]
[ 0 -1  0  2]
[-1 -1 -2  0]


In [4]:
E, F := FrobeniusFormAlternating(Matrix(Integers(),pol)); E,F;

[ 0  0  1  0]
[ 0  0  0  1]
[-1  0  0  0]
[ 0 -1  0  0]

[ 1  0  0  0]
[-1  1  0  0]
[ 0  0  0  1]
[-2  0  1  0]


In [5]:
ReconstructCurve(Pi*Transpose(ChangeRing(F, C)), Q);

Hyperelliptic Curve defined by y^2 = -19/4*x^6 + 65/2*x^5 - 275/4*x^4 + 143/2*x^3 - 83/2*x^2 + 13*x - 7/4 over Rational Field
Mapping from: FldRat: Q to FldRat: Q
true


In [6]:
H:=$1;
Conductor(H);

529


In [8]:
R<x> := PolynomialRing(Rationals()); C := HyperellipticCurve(R![0, 0, 0, 0, 0, -1], R![1, 1, 0, 1]);
IsIsomorphic(C, H);

false


In [9]:
G2Invariants(C);
G2Invariants(H);

[ -1804229351/529, -39370210/529, 3145584/529 ]
[ -59797108943/148035889, 777839062/6436343, -9815520/279841 ]


In [10]:
IsIsogenousPeriodMatrices(PeriodMatrix(C), PeriodMatrix(H));

true 
[-2  0 -1  1]
[ 2 -1 -1  1]
[ 2 -3 -2  1]
[ 1 -1  1  0]

[1.828779826051639971545253677288545535123055991716477857944201349164212217450781113080716834976275247E-99 - 1.000113967371990609438810604767173339520421245469948828563235112824178556418395921216017019127650526E-99*$.1 -1.000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000006 - 5.998451406983345463308223426360256168061097961111054692744224884282517368518370179257673505348207507E-100*$.1]
[1.000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000003 - 4.496048058676761355825367316966712289719036581197493171264186422383695563898770949395219367239036070E-100*$.1 -2.928905190160829641927945342532436208595519361733421569363759973270808629511016626418335556016690826E-99 - 8.000911738975924875510484838137386716163369963759590628505880902593428451347167369728136153021204208E-100*$.1]


In [11]:
_,B,E:=IsIsogenousPeriodMatrices(PeriodMatrix(C), PeriodMatrix(H));

In [12]:
Determinant(B);

11


In [13]:
IsIsomorphicBigPeriodMatrices(PeriodMatrix(C), PeriodMatrix(H));

false 
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]

[0.0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 0.0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000]
[0.0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 0.0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000]


In [14]:
Factorization(Integers()!Discriminant(H));

[ <23, 6> ]


In [15]:
Factorization(Integers()!Discriminant(C));

[ <23, 2> ]


# Button time:

In [10]:
function GetCurve(N : prec := 80, ncoeffs := 10000)
    SetDefaultRealFieldPrecision(prec + 10);
    C:=ComplexFieldExtra(prec);
    Q:=RationalsExtra(prec);
    Hs := [];
    for A in Decomposition(JZero(N)) do
        if Dimension(A) ne 2 then continue; end if;
        print A;
        Pi := Matrix(Periods(A, ncoeffs)); // no control over precision really, instead use Eran's code
        print "Periods computed";
        // Change convention
        Pi := Transpose(ChangeRing(Pi, C));
        g := #Rows(Pi);
        P1 := Submatrix(Pi,1,1,g,g);
        P2 := Submatrix(Pi,1,g+1,g,g);
        Pi = HorizontalJoin(P2,P1);
        _, pol := SomePrincipalPolarization(Pi); pol;
        print "Principal polarization found";
        E, F := FrobeniusFormAlternating(Matrix(Integers(), pol)); E,F;
        H := ReconstructCurve(Pi*Transpose(ChangeRing(F, C)), Q);
        // TODO can we twist it, yes we can
        print "Curve found";
        print H;
        Append(~Hs, <Newform(A), H>);
    end for;
    return Hs;
end function;

In [2]:
SetVerbose("CurveRec",2);

## 23

In [3]:
GetCurve(23);

Modular abelian variety 23A of dimension 2, level 23 and conductor 23^2 over Q
Periods computed
[0.59153223605591049412844857456813206387023215502104975359443796091010267748572892 - 1.6874592734680125399313535764556124833596758476471892852623068887203284395879923*C.1 -0.59153223605591049412844857456813206387023215502104975359443796091010267748572892 - 1.6874592734680125399313535764556124833596758476471892852623068887203284395879923*C.1 -1.3543385605139576628095288989023432177531386555833329556794417959366338520677597 - 1.0837716284893304295801997816494484515107861906527159591608828822124678802648372*C.1 -1.5256126489160943373621606486684223077658130011245664041700076700530623491640615]
[0.76280632445804716868108032433421115388290650056228320208500383502653117458203077 - 0.60368764497868211035115379480616403184888965699447332610142400650786055932315512*C.1 -0.76280632445804716868108032433421115388290650056228320208500383502653117458203077 - 0.60368764497868211035115379480616403184888965

## 31

In [20]:
GetCurve(31);

Modular abelian variety JZero(31) of dimension 2 and level 31 over Q
Periods computed
[-0.25655036936015153745832296033861323428313181609194429941647634781274790392434267 - 1.1714841244880598206273447539570668483414813402875243650540357340737011382235563*I -0.67414756541403061635405536527069083259488805963099862373196577348134018779676010 - 1.7291583732029589894305762888156166618026060718043778091564038683160744408709616*I -1.3482951308280612327081107305413816651897761192619972474639315469626803755935202 -1.8613958695483643076247566512186081337560397514458858462968842425881761834422055]
[0.67414756541403061635405536527069083259488805963099862373196577348134018779676000 + 1.7291583732029589894305762888156166618026060718043778091564038683160744408709617*I -0.41759719605387907889573240493207759831175624353905432431548942566859228387241792 - 0.55767424871489916880323153485854981346112473151685344410236813424237330264740517*I -0.83519439210775815779146480986415519662351248707810864863097885

In [21]:
H31 := $1;

In [22]:
Discriminant(H31);

923521


In [25]:
R<x> := PolynomialRing(Rationals()); C31 := HyperellipticCurve(R![-3, -2, 3, 4, -5], R![1, 0, 1, 1]);
IsIsomorphicBigPeriodMatrices(PeriodMatrix(C31), PeriodMatrix(H31));


>> IsIsomorphicBigPeriodMatrices(PeriodMatrix(C31), PeriodMatrix(H31));
                                                                 ^
User error: Identifier 'H31' has not been declared or assigned


## 35

In [34]:
GetCurve(35);

Modular abelian variety 35B of dimension 2, level 5*7 and conductor 5^2*7^2 over Q
Periods computed
[2.0344845156385959587189816046261414363352354842742126496144678589164768743131624 + 3.4297156012533748377208689741567976283361400315957379944250789178846292769250282*I 3.4297156012533748377208689741567976283361400315957379944250789178846292769250282*I 0.34137737790521970185855171439075200617921139250668418599842392117685468822211667 + 2.7967836865569805000651056664007522880276526219964776184225553808924634644585069*I -1.6931071377333762568604298902353894301560240917675284636160439377396221860910457 + 0.63293191469639433765576330775604534030848740959926037600252353699216581246652131*I]
[1.3551746977763371181099603462742300741618209169523173942116389335989303116238128 - 0.22449698561694937177445393578315406677554759829967412260374619247899150676473582*I -0.22449698561694937177445393578315406677554759829967412260374619247899150676473582*I 1.6931071377333762568604298902353894301560240917675

In [35]:
H35 := $1[1];

In [40]:
print Discriminant(H35);
print Conductor(H35);

-52521875/1024
1225


In [39]:
R<x> := PolynomialRing(Rationals()); C35 := HyperellipticCurve(R![2, 1, 1, 2], R![0, 0, 1, 1]);
_, B, E := IsIsogenousPeriodMatrices(PeriodMatrix(C35), PeriodMatrix(H35));
Determinant(B);

4


In [41]:
GetCurve(39);

Modular abelian variety 39B of dimension 2, level 3*13 and conductor 3^2*13^2 over Q
Periods computed
[-1.9479957727195430887104091534008201605385193314059003365302071512467692042689652 + 3.2850353304939402127150869938619129658153557140463096967553528860290365581524110*I -2.1381363490931733820682900560011367073668748864781633554110761786565589888298268 + 2.6189598960494736394824076964965531813842451286522630532919517922715824580998191*I -2.1381363490931733820682900560011367073668748864781633554110761786565589888298268 + 0.66607543444446657323267929736535978443111058539404664346340109375745410005259195*I 1.3321508688889331464653585947307195688622211707880932869268021875149082001051839*I]
[-2.3282769254668036754261709586014532541952304415504263742919452060663487733906897 + 1.9528844616050070662497283991311933969531345432582164098285506985141283580472269*I 0.19014057637363029335788090260031654682835555507226301888086902740978978456086153 + 0.66607543444446657323267929736535978443111058539

In [42]:
H39 := $1[1];

In [44]:
print Discriminant(H39);
print Conductor(H39);

-4804839/1024
1521


In [47]:
R<x> := PolynomialRing(Rationals()); C39 := HyperellipticCurve(R![2, 3, 4, 1, 1], R![1, 0, 0, 1]);
_, B, E := IsIsogenousPeriodMatrices(PeriodMatrix(C39), PeriodMatrix(H39));
print Determinant(B);
IsIsomorphicBigPeriodMatrices(PeriodMatrix(C39), PeriodMatrix(H39));

2
false 
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]

[0.0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 0.0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000]
[0.0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 0.0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000]


# 29

In [5]:
GetCurve(29);

Modular abelian variety 29A of dimension 2, level 29 and conductor 29^2 over Q
Periods computed
[-0.37654698724107982110198349672387118556352867851261276291164560608602746481049418 - 1.8013180138484217343811640890994647590687462484108594261459528492849284189084249*I -0.75309397448215964220396699344774237112705735702522552582329121217205492962098836 -1.2674667407397804936201219032113335846470358605888944793017616699373513186293436 - 1.1808874900527529913958134087839717838526979128417611497003284332282471408594112*I -1.7818395069974013450362768129749247981670143641525634327802321277026477076376988]
[-0.51437276625762085141615490976359121351997850356366895347847045776529638900835666 - 1.1808874900527529913958134087839717838526979128417611497003284332282471408594110*I -1.0287455325152417028323098195271824270399570071273379069569409155305927780167133 -0.37654698724107982110198349672387118556352867851261276291164560608602746481049378 + 0.560456966257084248410462728468478808636649577272662873

done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...

done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...

done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...

done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...

done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...

done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...

done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...

done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...

# many examples

In [6]:
for N in [43,51,55] do
  print N;
  GetCurve(N);
end for;

43
Modular abelian variety 43B of dimension 2, level 43 and conductor 43^2 over Q
Periods computed
[-1.0500562322397875607331822022848449153992969834750538682243334591090998566379293 - 1.6132037140947790563841652256125772943637187377240102190039319263681981360885706*I 0.59815631621097967355674974987698151087489622163873501071687546045009879640396470 - 1.9200856386057581061498709227356828066526778164128677957111401229077917376383028*I -0.59815631621097967355674974987698151087489622163873501071687546045009879640396470 - 1.9200856386057581061498709227356828066526778164128677957111401229077917376383028*I -2.1001124644795751214663644045696898307985939669501077364486669182181997132758586]
[0.22594995801440394358821622620393170226220038091815942875372899932950053011698157 + 1.7666446763502685812670180741741300505081982770684390073575360246379949368634361*I 0.82410627422538361714496597608091321313709660255689443947060445977959932652094767 - 0.153440962255489524882852848561552756144479539344428

done.

Eigenvalues of imaginary part of reduced tau:
[ 0.73185, 1.4656 ]

Calculating theta derivatives...
done calculating theta derivatives.

Identifying correct twist...

done identifying correct twist.

Algebraizing...
done.

Check for isomorphism...
done.
Curve found
Hyperelliptic Curve defined by y^2 = -6177/38416*x^6 + 7295/19208*x^5 + 17777/19208*x^4 + 4705/9604*x^3 + 3383/38416*x^2 + 95/19208*x - 45/4802 over Rational Field
[
Hyperelliptic Curve defined by y^2 = -6177/38416*x^6 + 7295/19208*x^5 + 17777/19208*x^4 + 4705/9604*x^3 + 3383/38416*x^2 + 95/19208*x - 45/4802 over Rational Field
]


# mf_newforms

In [5]:
load "mf_newforms.m";

Loading "mf_newforms.m"


In [ ]:
labels;

In [17]:
D := AssociativeArray(Integers());
for l in labels do
  N := StringToInteger(Split(l, ".")[1]);
  print N;
  if not IsDefined(D,N) then
      for Cs in GetCurve(N) do
          f,C := Explode(Cs);
          assert IsCorrectTwist(C, f);
      end for;
      D[N] := true;
  end if;
end for;

23
Modular abelian variety 23A of dimension 2, level 23 and conductor 23^2 over Q
Periods computed
[0.59153223605591049412844857456813206387023215502104975359443796091010267748572892 - 1.6874592734680125399313535764556124833596758476471892852623068887203284395879923*C.1 -0.59153223605591049412844857456813206387023215502104975359443796091010267748572892 - 1.6874592734680125399313535764556124833596758476471892852623068887203284395879923*C.1 -1.3543385605139576628095288989023432177531386555833329556794417959366338520677597 - 1.0837716284893304295801997816494484515107861906527159591608828822124678802648372*C.1 -1.5256126489160943373621606486684223077658130011245664041700076700530623491640615]
[0.76280632445804716868108032433421115388290650056228320208500383502653117458203077 - 0.60368764497868211035115379480616403184888965699447332610142400650786055932315512*C.1 -0.76280632445804716868108032433421115388290650056228320208500383502653117458203077 - 0.60368764497868211035115379480616403184888

done calculating theta derivatives.

Identifying correct twist...

done identifying correct twist.

Algebraizing...
done.

Check for isomorphism...
done.
Curve found
Hyperelliptic Curve defined by y^2 = -11/4*x^6 - 37/2*x^5 - 191/4*x^4 - 113/2*x^3 - 63/2*x^2 - 8*x - 3/4 over Rational Field
skipping
31
35
Modular abelian variety 35B of dimension 2, level 5*7 and conductor 5^2*7^2 over Q
Periods computed
[2.0344845156385959587189816046261414363352354842742126496144678589164768743131618 + 3.4297156012533748377208689741567976283361400315957379944250789178846292769250282*I 3.4297156012533748377208689741567976283361400315957379944250789178846292769250282*I 0.34137737790521970185855171439075200617921139250668418599842392117685468822211660 + 2.7967836865569805000651056664007522880276526219964776184225553808924634644585070*I -1.6931071377333762568604298902353894301560240917675284636160439377396221860910452 + 0.63293191469639433765576330775604534030848740959926037600252353699216581246652126*I]
[

done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...

done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...

done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...

done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...

done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...

done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...

done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...

done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...

In [ ]:
GetCurve(69 : prec := 40);

Modular abelian variety 69B of dimension 2, level 3*23 and conductor 3^2*23^2 over Q
Periods computed
[-2.560521826397713846969743991166039659475 - 3.751673231877022734101275412521215211366*C.1 1.474516801169708985940117595729808272439 -5.345529420184391292281072934302963757630E-51 + 7.632476064806356737352600669303591794467*C.1 -9.544594056304554651759840769521504136267 - 7.632476064806356737352600669303591794467*C.1]
[-5.509555428737131818849979182625656204353 + 3.803325072297947241761295350225679760060*C.1 -2.498725531728794524728015192196224136229 0.02582592021046225383000996885223227434708*C.1 -3.522934262287880063515912788662640000019 - 0.02582592021046225383000996885223227434708*C.1] = [-5.345529420184391292281072934302963757630E-51 + 7.632476064806356737352600669303591794467*C.1 -9.544594056304554651759840769521504136267 - 7.632476064806356737352600669303591794467*C.1 -2.560521826397713846969743991166039659475 - 3.751673231877022734101275412521215211366*C.1 1.474516801169708985

# IsCorrectTwist

In [4]:
function IsCorrectTwist(C, f)
    M := ModularAbelianVariety(f);
    D := Discriminant(C);
    N := Level(f);
    for p in PrimesUpTo(1000) do
        if (Numerator(D) mod p eq 0) or (N mod p eq 0) then 
            print "skipping";
            print p;
            continue;
        end if;
        if EulerFactor(C,p) ne Reverse(FrobeniusPolynomial(M, p)) then
            print p;
            print EulerFactor(C,p);
            print Reverse(FrobeniusPolynomial(M, p));
            return false;
        end if;
    end for;
    return true;
end function;

Example to test this for 31

In [93]:
R<x> := PolynomialRing(Rationals()); C31 := HyperellipticCurve(R![-3, -2, 3, 4, -5], R![1, 0, 1, 1]);

In [94]:
IsCorrectTwist(C31, Newform("31A"));

skipping
31
true


In [97]:
ff := HyperellipticPolynomials(SimplifiedModel(C31));
R<x> := PolynomialRing(Rationals()); C31t4 := HyperellipticCurve(4*ff);
IsCorrectTwist(C31t4, Newform("31A"));

skipping
2
skipping
31
true


In [99]:
ff := HyperellipticPolynomials(SimplifiedModel(C31));
R<x> := PolynomialRing(Rationals()); C31t3 := HyperellipticCurve(3*ff);
IsCorrectTwist(C31t3, Newform("31A"));

skipping
2
skipping
3
5
25*$.1^4 + 10*$.1^3 + 11*$.1^2 + 2*$.1 + 1
25*$.1^4 - 10*$.1^3 + 11*$.1^2 - 2*$.1 + 1
false


In [100]:
ff := HyperellipticPolynomials(SimplifiedModel(C31));
R<x> := PolynomialRing(Rationals()); C31t6 := HyperellipticCurve(6*ff);
IsCorrectTwist(C31t6, Newform("31A"));

skipping
2
skipping
3
7
49*$.1^4 - 28*$.1^3 + 13*$.1^2 - 4*$.1 + 1
49*$.1^4 + 28*$.1^3 + 13*$.1^2 + 4*$.1 + 1
false


In [118]:
C31t7 := QuadraticTwist(C31, 7);
IsCorrectTwist(C31t7, Newform("31A"));

skipping
2
5
25*$.1^4 + 10*$.1^3 + 11*$.1^2 + 2*$.1 + 1
25*$.1^4 - 10*$.1^3 + 11*$.1^2 - 2*$.1 + 1
false


# Noam example

In [43]:
R<x> := PolynomialRing(Rationals()); C69b := HyperellipticCurve(
 -x^6 + 12*x^5 - 25*x^4 - 48*x^3 + 65*x^2 + 150*x + 66);
C69b;
IsCorrectTwist(C69b, Newform("69B"));

Hyperelliptic Curve defined by y^2 = -x^6 + 12*x^5 - 25*x^4 - 48*x^3 + 65*x^2 + 150*x + 66 over Rational Field
skipping
2
skipping
3
skipping
23
true


In [44]:
PeriodMatrix(C69b);

[-6.7630447000723039918636989450404632897222188747432E-69 - 0.17111755418101153913710365440669687947906447857228*$.1 -0.18200638546513468962677259942777000774048182184795 - 0.25990457129782509043440672771657435351198164441090*$.1 -0.15732445307358912460337199953149202167147327845303 + 3.8251699215392860485896941636603871627095539099964E-66*$.1 -0.18200638546513468962677259942777000774048182184795 + 0.25990457129782509043440672771657435351198164441090*$.1]
[-2.2607443657322663968310728468017407804882647184117E-68 - 0.51980914259565018086881345543314870702396328882181*$.1 0.20668831785668025465017319932404799380949036524287 + 0.17757403423362710259460614661975494806583433167726*$.1 -0.72802554186053875850709039771108003096192728739180 - 3.0059914271648836013353469068786454098595544496991E-65*$.1 0.20668831785668025465017319932404799380949036524287 - 0.17757403423362710259460614661975494806583433167726*$.1]


In [48]:
prec := 60;
ncoeffs := 10000;
SetDefaultRealFieldPrecision(prec + 10);
C:=ComplexFieldExtra(prec);
Q:=RationalsExtra(prec);
A := ModularAbelianVariety(Newform("69B"));
Pi := Matrix(Periods(A, ncoeffs)); // no control over precision really, instead use Eran's code
print "Periods computed";
// Change convention
Pi := Transpose(ChangeRing(Pi, C));
g := #Rows(Pi);
P1 := Submatrix(Pi,1,1,g,g);
P2 := Submatrix(Pi,1,g+1,g,g);
Pi = HorizontalJoin(P2,P1);
//_, pol := SomePrincipalPolarization(Pi); pol;

Periods computed
[-2.56052182639771384696974399116603965947507452032710532179642 - 3.75167323187702273410127541252121521136587882238009928647868*C.1 1.47451680116970898594011759572980827243869861095060166376772 7.24454326306136989400729543271023342454602495851131055166609E-71 + 7.63247606480635673735260066930359179446715470685979204142447*C.1 -9.54459405630455465175984076952150413626624487350601563489599 - 7.63247606480635673735260066930359179446715470685979204142447*C.1]
[-5.50955542873713181884997918262565620435247174222830864933186 + 3.80332507229794724176129535022567976006003764721993667386553*C.1 -2.49872553172879452472801519219622413622872841908144379248629 0.0258259202104622538300099688522322743470794124199186936934243*C.1 -3.52293426228788006351591278866264000001875822721228592120485 - 0.0258259202104622538300099688522322743470794124199186936934243*C.1] = [7.24454326306136989400729543271023342454602495851131055166609E-71 + 7.63247606480635673735260066930359179446715470685979204

In [55]:
IsIsomorphicBigPeriodMatrices(Pi, ChangeRing(PeriodMatrix(C69b),C));


IsIsomorphicBigPeriodMatrices(
PM1: [-2.56052182639771384696974399116603965947507452032710532179...,
PM2: [-6.76304470007230399186369894504046328972221887474324200674...
)
IsIsomorphicSmallPeriodMatrices(
tau1: [-0.28273438844193450134029184483692943878340278630824774701...,
tau2: [-0.01231227728406741138002615037016244181440083758383276450...
)
D2IsIsomorphic(
tau1: [-0.01231227728406741138002615037016244181440083758383276450...,
tau2: [-0.28273438844193450134029184483692943878340278630824774701...,
pres: 48
)
In file "/Applications/Magma/package/Geometry/CrvAnJac/iso.m", line 421, column 54:
>>   ftau2, smat2 := To2DUpperHalfSpaceFundamentalDomian(tau2);
                                                        ^
Runtime error in 'To2DUpperHalfSpaceFundamentalDomian': The argument should be a symmetric matrix.



In [57]:
_, B:=SomePolarization(Pi);
Determinant(B);

4


In [69]:
E, F := FrobeniusFormAlternating(Matrix(Integers(), B)); E,F;


[ 0  0  1  0]
[ 0  0  0  2]
[-1  0  0  0]
[ 0 -2  0  0]

[ 0  0  1  0]
[ 0  1  1  1]
[ 0  1  0  0]
[ 1 -1  2  0]


In [78]:
( E * E);

[-1  0  0  0]
[ 0 -4  0  0]
[ 0  0 -1  0]
[ 0  0  0 -4]


In [76]:
try
IsIsomorphicBigPeriodMatrices(Pi * ChangeRing(Transpose(F),C), ChangeRing(PeriodMatrix(C69b),C));
catch e; print e`Object; end try;

Runtime error in 'To2DUpperHalfSpaceFundamentalDomian': The argument should be a symmetric matrix.



In [88]:
IsBigPeriodMatrix(Pi * ChangeRing((E), C) * ChangeRing(Transpose(F),C));

false


In [60]:
IsIsomorphicBigPeriodMatrices(Pi * ChangeRing(Transpose(F),C), ChangeRing(PeriodMatrix(C69b),C));


IsIsomorphicBigPeriodMatrices(
PM1: [7.244543263061369894007295432710233424546024958511310551666...,
PM2: [-6.76304470007230399186369894504046328972221887474324200674...
)
IsIsomorphicSmallPeriodMatrices(
tau1: [-0.26123465322408195518517677293034587850162621443078377876...,
tau2: [-0.01231227728406741138002615037016244181440083758383276450...
)
D2IsIsomorphic(
tau1: [-0.01231227728406741138002615037016244181440083758383276450...,
tau2: [-0.26123465322408195518517677293034587850162621443078377876...,
pres: 48
)
In file "/Applications/Magma/package/Geometry/CrvAnJac/iso.m", line 421, column 54:
>>   ftau2, smat2 := To2DUpperHalfSpaceFundamentalDomian(tau2);
                                                        ^
Runtime error in 'To2DUpperHalfSpaceFundamentalDomian': The argument should be a symmetric matrix.



# FindCorrectTwist

A naive function to stitch together a quadratic twist by comparing euler factors.

In [32]:
function BigCRT(moduli)
    oldmod := 1;
    oldvals := [0];
    for E in moduli do
        m, sols := Explode(E);
        print m;
        newvals := [];
        for sol in sols do
            for ov in oldvals do
                Append(~newvals,CRT([ov, sol], [oldmod, m]));
            end for;
        end for;
        oldmod *:= m;
        oldvals := newvals;
    end for;
    return [oldval - oldmod * (oldval div (oldmod div 2)) : oldval in oldvals];
end function;

// given two lists of primes find integers that are squares mod the first and non-squares mod the second

function SquaresMod(mods, nonmods)
    inp := [];
    for m in mods do
       Append(~inp, <m, [i : i in [0.. m-1] | KroneckerSymbol(i, m) eq 1 ]>);
    end for;
    for m in nonmods do
       Append(~inp, <m, [i : i in [0.. m-1] | KroneckerSymbol(i, m) eq -1 ]>);
    end for;
    return BigCRT(inp);
end function;
function SmallestSquareMod(mods,nonmods)
    L := SquaresMod(mods, nonmods);
    L2 := [<Abs(l), l> : l in L];
    print L2;
    return Sort(L2)[1][2];
end function;

In [33]:
BigCRT([<2,[1]>, <3, [-1,0]>]);

2
3
[ -1, -3 ]


In [34]:
SmallestSquareMod([5,7], [11]);

5
7
11
[ <174, -174>, <134, 134>, <156, 156>, <79, 79>, <46, 46>, <31, -31>, <104, -104>, <181, -181>, <159, -159>, <149, 149>, <116, 116>, <39, 39>, <106, 106>, <29, 29>, <51, 51>, <26, -26>, <59, -59>, <136, -136>, <69, -69>, <146, -146>, <124, -124>, <184, 184>, <151, 151>, <74, 74>, <34, -34>, <111, -111>, <89, -89>, <166, -166>, <186, 186>, <109, 109> ]
-26


In [35]:
29 mod 5;
29 mod 7;
29 mod 11;

4
1
7


In [36]:
function FindCorrectTwist(C, f)
    M := ModularAbelianVariety(f);
    D := Discriminant(C);
    N := Level(f);
    sqps := [];
    nsqps := [];
    for p in PrimesUpTo(12) do
        if (Numerator(D) mod p eq 0) or (N mod p eq 0) then 
            print "skipping";
            print p;
            continue;
        end if;
        if EulerFactor(C,p) ne Reverse(FrobeniusPolynomial(M, p)) then
            Append(~nsqps, p);
        else
            Append(~sqps, p);
        end if;
    end for;
    return SmallestSquareMod(sqps, nsqps);
end function;

In [37]:
C31t := QuadraticTwist(C31, -5);
FindCorrectTwist(C31t, Newform("31A"));

skipping
2
skipping
5
3
7
11
[ <20, -20>, <79, 79>, <46, 46>, <104, -104>, <5, -5>, <38, -38>, <106, 106>, <26, -26>, <59, -59>, <85, 85>, <47, -47>, <80, -80>, <43, 43>, <89, -89>, <109, 109> ]
-5
