Magma (+CHIMP) notebook to find curves whose Jacobians are isogeny factors of the Jacobians of modular curves.
Via the period matrix, for now only for genus 2 curves where we have RM.

Example 2:
https://www.lmfdb.org/ModularForm/GL2/Q/holomorphic/23/2/a/a/
should give
https://www.lmfdb.org/Genus2Curve/Q/529/a/529/1
or something isogenous

## J_0(23)

In [1]:
X  := JZero(23);
X;

Modular abelian variety JZero(23) of dimension 2 and level 23 over Q


In [2]:
prec := 80;
SetDefaultRealFieldPrecision(prec);
C:=ComplexFieldExtra(prec);
Q:=RationalsExtra(prec);
Pi := Matrix(Periods(X, 10000)); // no control over precision really, instead use Eran's code
print Parent(Pi);
Pi := Transpose(ChangeRing(Pi, C));
g := #Rows(Pi);
P1 := Submatrix(Pi,1,1,g,g);
P2 := Submatrix(Pi,1,g+1,g,g);
Pi = HorizontalJoin(P2,P1);

Full KMatrixSpace of 4 by 2 matrices over C
[0.59153223605591049412844857456813206387023215502104975359443796091010267748572893 - 1.6874592734680125399313535764556124833596758476471892852623068887203284395879924*C.1 -0.59153223605591049412844857456813206387023215502104975359443796091010267748572893 - 1.6874592734680125399313535764556124833596758476471892852623068887203284395879924*C.1 -1.3543385605139576628095288989023432177531386555833329556794417959366338520677597 - 1.0837716284893304295801997816494484515107861906527159591608828822124678802648372*C.1 -1.5256126489160943373621606486684223077658130011245664041700076700530623491640616]
[0.76280632445804716868108032433421115388290650056228320208500383502653117458203096 - 0.60368764497868211035115379480616403184888965699447332610142400650786055932315512*C.1 -0.76280632445804716868108032433421115388290650056228320208500383502653117458203096 - 0.60368764497868211035115379480616403184888965699447332610142400650786055932315512*C.1 -0.59153223

In [3]:
_,pol := SomePrincipalPolarization(Pi); pol;

[ 0  0  0  1]
[ 0  0  1  1]
[ 0 -1  0  2]
[-1 -1 -2  0]


In [4]:
E, F := FrobeniusFormAlternating(Matrix(Integers(),pol)); E,F;

[ 0  0  1  0]
[ 0  0  0  1]
[-1  0  0  0]
[ 0 -1  0  0]

[ 1  0  0  0]
[-1  1  0  0]
[ 0  0  0  1]
[-2  0  1  0]


In [5]:
ReconstructCurve(Pi*Transpose(ChangeRing(F, C)), Q);

Hyperelliptic Curve defined by y^2 = -19/4*x^6 + 65/2*x^5 - 275/4*x^4 + 143/2*x^3 - 83/2*x^2 + 13*x - 7/4 over Rational Field
Mapping from: FldRat: Q to FldRat: Q
true


In [6]:
H:=$1;
Conductor(H);

529


In [8]:
R<x> := PolynomialRing(Rationals()); C := HyperellipticCurve(R![0, 0, 0, 0, 0, -1], R![1, 1, 0, 1]);
IsIsomorphic(C, H);

false


In [9]:
G2Invariants(C);
G2Invariants(H);

[ -1804229351/529, -39370210/529, 3145584/529 ]
[ -59797108943/148035889, 777839062/6436343, -9815520/279841 ]


In [10]:
IsIsogenousPeriodMatrices(PeriodMatrix(C), PeriodMatrix(H));

true 
[-2  0 -1  1]
[ 2 -1 -1  1]
[ 2 -3 -2  1]
[ 1 -1  1  0]

[1.828779826051639971545253677288545535123055991716477857944201349164212217450781113080716834976275247E-99 - 1.000113967371990609438810604767173339520421245469948828563235112824178556418395921216017019127650526E-99*$.1 -1.000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000006 - 5.998451406983345463308223426360256168061097961111054692744224884282517368518370179257673505348207507E-100*$.1]
[1.000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000003 - 4.496048058676761355825367316966712289719036581197493171264186422383695563898770949395219367239036070E-100*$.1 -2.928905190160829641927945342532436208595519361733421569363759973270808629511016626418335556016690826E-99 - 8.000911738975924875510484838137386716163369963759590628505880902593428451347167369728136153021204208E-100*$.1]


In [11]:
_,B,E:=IsIsogenousPeriodMatrices(PeriodMatrix(C), PeriodMatrix(H));

In [12]:
Determinant(B);

11


In [13]:
IsIsomorphicBigPeriodMatrices(PeriodMatrix(C), PeriodMatrix(H));

false 
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]

[0.0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 0.0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000]
[0.0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 0.0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000]


In [14]:
Factorization(Integers()!Discriminant(H));

[ <23, 6> ]


In [15]:
Factorization(Integers()!Discriminant(C));

[ <23, 2> ]


# Button time:

In [2]:
function GetCurve(N)
    Hs := [];
    for A in Decomposition(JZero(N)) do
        if Dimension(A) ne 2 then continue; end if;
        print A;
        prec := 80;
        SetDefaultRealFieldPrecision(prec);
        C:=ComplexFieldExtra(prec);
        Q:=RationalsExtra(prec);
        Pi := Matrix(Periods(A, 10000)); // no control over precision really, instead use Eran's code
        print "Periods computed";
        // Change convention
        Pi := Transpose(ChangeRing(Pi, C));
        g := #Rows(Pi);
        P1 := Submatrix(Pi,1,1,g,g);
        P2 := Submatrix(Pi,1,g+1,g,g);
        Pi = HorizontalJoin(P2,P1);
        _, pol := SomePrincipalPolarization(Pi); pol;
        print "Principal polarization found";
        E, F := FrobeniusFormAlternating(Matrix(Integers(), pol)); E,F;
        H := ReconstructCurve(Pi*Transpose(ChangeRing(F, C)), Q);
        // TODO can we twist it, yes we can
        print "Curve found";
        print H;
        Append(~Hs, H);
    end for;
    return Hs;
end function;

In [3]:
SetVerbose("CurveRec",2);

## 23

In [17]:
GetCurve(23);

Modular abelian variety JZero(23) of dimension 2 and level 23 over Q
Periods computed
[0.59153223605591049412844857456813206387023215502104975359443796091010267748572911 - 1.6874592734680125399313535764556124833596758476471892852623068887203284395879923*I -0.59153223605591049412844857456813206387023215502104975359443796091010267748572911 - 1.6874592734680125399313535764556124833596758476471892852623068887203284395879923*I -1.3543385605139576628095288989023432177531386555833329556794417959366338520677594 - 1.0837716284893304295801997816494484515107861906527159591608828822124678802648372*I -1.5256126489160943373621606486684223077658130011245664041700076700530623491640606]
[0.76280632445804716868108032433421115388290650056228320208500383502653117458203078 - 0.60368764497868211035115379480616403184888965699447332610142400650786055932315493*I -0.76280632445804716868108032433421115388290650056228320208500383502653117458203078 - 0.60368764497868211035115379480616403184888965699447332610142400

In [1]:
for N in [23,29,31,35,39,43,51,55] do
  print N;
  GetCurve(N);
end for;


>>   GetCurve(N);
     ^
User error: Identifier 'GetCurve' has not been declared or assigned


## 31

In [20]:
GetCurve(31);

Modular abelian variety JZero(31) of dimension 2 and level 31 over Q
Periods computed
[-0.25655036936015153745832296033861323428313181609194429941647634781274790392434267 - 1.1714841244880598206273447539570668483414813402875243650540357340737011382235563*I -0.67414756541403061635405536527069083259488805963099862373196577348134018779676010 - 1.7291583732029589894305762888156166618026060718043778091564038683160744408709616*I -1.3482951308280612327081107305413816651897761192619972474639315469626803755935202 -1.8613958695483643076247566512186081337560397514458858462968842425881761834422055]
[0.67414756541403061635405536527069083259488805963099862373196577348134018779676000 + 1.7291583732029589894305762888156166618026060718043778091564038683160744408709617*I -0.41759719605387907889573240493207759831175624353905432431548942566859228387241792 - 0.55767424871489916880323153485854981346112473151685344410236813424237330264740517*I -0.83519439210775815779146480986415519662351248707810864863097885

In [21]:
H31 := $1;

In [22]:
Discriminant(H31);

923521


In [23]:
R<x> := PolynomialRing(Rationals()); C31 := HyperellipticCurve(R![-3, -2, 3, 4, -5], R![1, 0, 1, 1]);
IsIsomorphicBigPeriodMatrices(PeriodMatrix(C31), PeriodMatrix(H31));

true 
[-1  0  1  0]
[ 0 -1  0  0]
[ 0  0 -1  0]
[ 0  0  0 -1]

[-1.000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 -1.428734239102843727769729435381676199314887493528498326518907304034540794883422744594310027325215037E-101*$.1]
[-2.000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 + 7.858038315065640502733511894599219096231881214406740795853990172189974371858825095268705150288682704E-101*$.1 1.000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 - 5.714936956411374911078917741526704797259549974113993306075629216138163179533690978377240109300860148E-101*$.1]


## 35

In [34]:
GetCurve(35);

Modular abelian variety 35B of dimension 2, level 5*7 and conductor 5^2*7^2 over Q
Periods computed
[2.0344845156385959587189816046261414363352354842742126496144678589164768743131624 + 3.4297156012533748377208689741567976283361400315957379944250789178846292769250282*I 3.4297156012533748377208689741567976283361400315957379944250789178846292769250282*I 0.34137737790521970185855171439075200617921139250668418599842392117685468822211667 + 2.7967836865569805000651056664007522880276526219964776184225553808924634644585069*I -1.6931071377333762568604298902353894301560240917675284636160439377396221860910457 + 0.63293191469639433765576330775604534030848740959926037600252353699216581246652131*I]
[1.3551746977763371181099603462742300741618209169523173942116389335989303116238128 - 0.22449698561694937177445393578315406677554759829967412260374619247899150676473582*I -0.22449698561694937177445393578315406677554759829967412260374619247899150676473582*I 1.6931071377333762568604298902353894301560240917675

In [35]:
H35 := $1[1];

In [40]:
print Discriminant(H35);
print Conductor(H35);

-52521875/1024
1225


In [39]:
R<x> := PolynomialRing(Rationals()); C35 := HyperellipticCurve(R![2, 1, 1, 2], R![0, 0, 1, 1]);
_, B, E := IsIsogenousPeriodMatrices(PeriodMatrix(C35), PeriodMatrix(H35));
Determinant(B);

4


In [41]:
GetCurve(39);

Modular abelian variety 39B of dimension 2, level 3*13 and conductor 3^2*13^2 over Q
Periods computed
[-1.9479957727195430887104091534008201605385193314059003365302071512467692042689652 + 3.2850353304939402127150869938619129658153557140463096967553528860290365581524110*I -2.1381363490931733820682900560011367073668748864781633554110761786565589888298268 + 2.6189598960494736394824076964965531813842451286522630532919517922715824580998191*I -2.1381363490931733820682900560011367073668748864781633554110761786565589888298268 + 0.66607543444446657323267929736535978443111058539404664346340109375745410005259195*I 1.3321508688889331464653585947307195688622211707880932869268021875149082001051839*I]
[-2.3282769254668036754261709586014532541952304415504263742919452060663487733906897 + 1.9528844616050070662497283991311933969531345432582164098285506985141283580472269*I 0.19014057637363029335788090260031654682835555507226301888086902740978978456086153 + 0.66607543444446657323267929736535978443111058539

In [42]:
H39 := $1[1];

In [44]:
print Discriminant(H39);
print Conductor(H39);

-4804839/1024
1521


In [47]:
R<x> := PolynomialRing(Rationals()); C39 := HyperellipticCurve(R![2, 3, 4, 1, 1], R![1, 0, 0, 1]);
_, B, E := IsIsogenousPeriodMatrices(PeriodMatrix(C39), PeriodMatrix(H39));
print Determinant(B);
IsIsomorphicBigPeriodMatrices(PeriodMatrix(C39), PeriodMatrix(H39));

2
false 
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]

[0.0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 0.0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000]
[0.0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 0.0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000]


# 29

In [5]:
GetCurve(29);

Modular abelian variety 29A of dimension 2, level 29 and conductor 29^2 over Q
Periods computed
[-0.37654698724107982110198349672387118556352867851261276291164560608602746481049418 - 1.8013180138484217343811640890994647590687462484108594261459528492849284189084249*I -0.75309397448215964220396699344774237112705735702522552582329121217205492962098836 -1.2674667407397804936201219032113335846470358605888944793017616699373513186293436 - 1.1808874900527529913958134087839717838526979128417611497003284332282471408594112*I -1.7818395069974013450362768129749247981670143641525634327802321277026477076376988]
[-0.51437276625762085141615490976359121351997850356366895347847045776529638900835666 - 1.1808874900527529913958134087839717838526979128417611497003284332282471408594110*I -1.0287455325152417028323098195271824270399570071273379069569409155305927780167133 -0.37654698724107982110198349672387118556352867851261276291164560608602746481049378 + 0.560456966257084248410462728468478808636649577272662873

done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...

done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...

done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...

done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...

done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...

done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...

done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...

done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...

# many examples

In [6]:
for N in [43,51,55] do
  print N;
  GetCurve(N);
end for;

43
Modular abelian variety 43B of dimension 2, level 43 and conductor 43^2 over Q
Periods computed
[-1.0500562322397875607331822022848449153992969834750538682243334591090998566379293 - 1.6132037140947790563841652256125772943637187377240102190039319263681981360885706*I 0.59815631621097967355674974987698151087489622163873501071687546045009879640396470 - 1.9200856386057581061498709227356828066526778164128677957111401229077917376383028*I -0.59815631621097967355674974987698151087489622163873501071687546045009879640396470 - 1.9200856386057581061498709227356828066526778164128677957111401229077917376383028*I -2.1001124644795751214663644045696898307985939669501077364486669182181997132758586]
[0.22594995801440394358821622620393170226220038091815942875372899932950053011698157 + 1.7666446763502685812670180741741300505081982770684390073575360246379949368634361*I 0.82410627422538361714496597608091321313709660255689443947060445977959932652094767 - 0.153440962255489524882852848561552756144479539344428

done.

Eigenvalues of imaginary part of reduced tau:
[ 0.73185, 1.4656 ]

Calculating theta derivatives...
done calculating theta derivatives.

Identifying correct twist...

done identifying correct twist.

Algebraizing...
done.

Check for isomorphism...
done.
Curve found
Hyperelliptic Curve defined by y^2 = -6177/38416*x^6 + 7295/19208*x^5 + 17777/19208*x^4 + 4705/9604*x^3 + 3383/38416*x^2 + 95/19208*x - 45/4802 over Rational Field
[
Hyperelliptic Curve defined by y^2 = -6177/38416*x^6 + 7295/19208*x^5 + 17777/19208*x^4 + 4705/9604*x^3 + 3383/38416*x^2 + 95/19208*x - 45/4802 over Rational Field
]


# mf_newforms

In [4]:
load "mf_newforms.m";

Loading "mf_newforms.m"


In [5]:
labels;

[* 23.2.a.a, 29.2.a.a, 31.2.a.a, 35.2.a.b, 39.2.a.b, 43.2.a.b, 51.2.a.b, 55.2.a.b, 62.2.a.b, 63.2.a.b, 65.2.a.b, 65.2.a.c, 67.2.a.b, 67.2.a.c, 68.2.a.a, 69.2.a.b, 73.2.a.b, 73.2.a.c, 74.2.a.a, 74.2.a.b, 77.2.a.d, 81.2.a.a, 82.2.a.b, 85.2.a.b, 85.2.a.c, 86.2.a.a, 86.2.a.b, 87.2.a.a, 88.2.a.b, 91.2.a.c, 93.2.a.a, 94.2.a.b, 98.2.a.b, 103.2.a.a, 104.2.a.b, 105.2.a.b, 107.2.a.a, 110.2.a.d, 113.2.a.b, 115.2.a.b, 117.2.a.b, 117.2.a.c, 122.2.a.b, 123.2.a.c, 125.2.a.a, 125.2.a.b, 129.2.a.c, 133.2.a.a, 133.2.a.b, 133.2.a.c, 135.2.a.c, 135.2.a.d, 136.2.a.c, 138.2.a.d, 141.2.a.f, 145.2.a.b, 147.2.a.d, 147.2.a.e, 148.2.a.b, 153.2.a.e, 154.2.a.d, 158.2.a.f, 160.2.a.c, 161.2.a.b, 165.2.a.a, 165.2.a.b, 166.2.a.b, 167.2.a.a, 169.2.a.a, 170.2.a.f, 172.2.a.b, 175.2.a.d, 175.2.a.e, 175.2.a.f, 176.2.a.d, 177.2.a.a, 177.2.a.b, 177.2.a.c, 178.2.a.c, 183.2.a.a, 184.2.a.e, 186.2.a.d, 187.2.a.c, 187.2.a.d, 188.2.a.a, 188.2.a.b, 189.2.a.e, 189.2.a.f, 190.2.a.d, 191.2.a.a, 193.2.a.a, 196.2.a.c, 199.2.a.a, 203.2.a

In [11]:
D := AssociativeArray(Integers());
for l in labels do
  N := StringToInteger(Split(l, ".")[1]);
  print N;
  if not IsDefined(D,N) then
      GetCurve(N);
      D[N] := true;
  end if;
end for;

23
Modular abelian variety 23A of dimension 2, level 23 and conductor 23^2 over Q
Periods computed
[0.59153223605591049412844857456813206387023215502104975359443796091010267748572887 - 1.6874592734680125399313535764556124833596758476471892852623068887203284395879924*C.1 -0.59153223605591049412844857456813206387023215502104975359443796091010267748572887 - 1.6874592734680125399313535764556124833596758476471892852623068887203284395879924*C.1 -1.3543385605139576628095288989023432177531386555833329556794417959366338520677597 - 1.0837716284893304295801997816494484515107861906527159591608828822124678802648372*C.1 -1.5256126489160943373621606486684223077658130011245664041700076700530623491640616]
[0.76280632445804716868108032433421115388290650056228320208500383502653117458203066 - 0.60368764497868211035115379480616403184888965699447332610142400650786055932315510*C.1 -0.76280632445804716868108032433421115388290650056228320208500383502653117458203066 - 0.60368764497868211035115379480616403184888

done calculating theta derivatives.

Identifying correct twist...

done identifying correct twist.

Algebraizing...
done.

Check for isomorphism...
done.
Curve found
Hyperelliptic Curve defined by y^2 = -3/4*x^6 - 7/2*x^5 - 11/4*x^4 + 9/2*x^3 + 3/2*x^2 - 2*x + 1/4 over Rational Field
[
Hyperelliptic Curve defined by y^2 = -3/4*x^6 - 7/2*x^5 - 11/4*x^4 + 9/2*x^3 + 3/2*x^2 - 2*x + 1/4 over Rational Field
]
35
Modular abelian variety 35B of dimension 2, level 5*7 and conductor 5^2*7^2 over Q
Periods computed
[2.0344845156385959587189816046261414363352354842742126496144678589164768743131615 + 3.4297156012533748377208689741567976283361400315957379944250789178846292769250293*I 3.4297156012533748377208689741567976283361400315957379944250789178846292769250293*I 0.34137737790521970185855171439075200617921139250668418599842392117685468822211604 + 2.7967836865569805000651056664007522880276526219964776184225553808924634644585085*I -1.6931071377333762568604298902353894301560240917675284636160439377

done calculating theta derivatives.

Identifying correct twist...

done identifying correct twist.

Algebraizing...
done.

Check for isomorphism...
done.
Curve found
Hyperelliptic Curve defined by y^2 = -3*x^6 + 10*x^5 - 12*x^4 + 7*x^3 - 3*x^2 + 7/8*x - 3/16 over Rational Field
[
Hyperelliptic Curve defined by y^2 = -3*x^6 + 10*x^5 - 12*x^4 + 7*x^3 - 3*x^2 + 7/8*x - 3/16 over Rational Field
]
51
Modular abelian variety 51B of dimension 2, level 3*17 and conductor 3^2*17^2 over Q
Periods computed
[-2.6909085440631801494597098583342721629288725061302089003813982426914456972406259 + 4.3250271979093630341534562602047256748137764554726262612544908782881549006175268*I -3.6866586108547366776495247363664851321893618747079838923560670777511032129053981 -7.3733172217094733552990494727329702643787237494159677847121341555022064258107962 + 8.1793777681217097436610829237316338520754650005821094111215735372133446606637297*I 3.686658610854736677649524736366485132189361874707983892356067077751103212905

done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...

done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...

done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...

done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...

done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...

done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...

done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...

done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...
done.

Minkowski reduction...
done.

Integral reduction...
done.

Gottschling reduction...

done calculating theta derivatives.

Identifying correct twist...

done identifying correct twist.

Algebraizing...
done.

Check for isomorphism...
done.
Curve found
Hyperelliptic Curve defined by y^2 = 13044/14641*x^6 + 9062/14641*x^5 - 2383/58564*x^4 - 14073/58564*x^3 - 48831/234256*x^2 - 10057/117128*x - 2235/234256 over Rational Field
Modular abelian variety N(31,62,1)(31A) of dimension 2, level 2*31 and conductor 31^2 over Q
Periods computed
[-0.25655036936015153745832296033861323428313181609194429941647634781274790392434250 - 1.1714841244880598206273447539570668483414813402875243650540357340737011382235566*I -0.67414756541403061635405536527069083259488805963099862373196577348134018779676043 - 1.7291583732029589894305762888156166618026060718043778091564038683160744408709617*I -1.3482951308280612327081107305413816651897761192619972474639315469626803755935209 -1.8613958695483643076247566512186081337560397514458858462968842425881761834422059]
[0.67414756541403061635405536527069083259

done calculating theta derivatives.

Identifying correct twist...

done identifying correct twist.

Algebraizing...
done.

Check for isomorphism...
done.
Curve found
Hyperelliptic Curve defined by y^2 = 9/16*x^6 + 9/8*x^3 - 1/48 over Rational Field
[
Hyperelliptic Curve defined by y^2 = 9/16*x^6 + 9/8*x^3 - 1/48 over Rational Field
]
65
Modular abelian variety 65B of dimension 2, level 5*13 and conductor 5^2*13^2 over Q
Periods computed
[-3.4117581563203973521179893601229704783677202070915001638169522180882551527205090 + 3.6424546101989341626532995529513491197720230226059206779083946484929131886409519*I 1.6330037578121721021142022204519054203259430538637730982371089636240100179899659 + 3.3750386810949145132930656740856855195837643236067037709607469822159356221441487*I -3.4117581563203973521179893601229704783677202070915001638169522180882551527205090 + 3.3750386810949145132930656740856855195837643236067037709607469822159356221441487*I -2.5223809570662847271160957902874379493468316304776

done calculating theta derivatives.

Identifying correct twist...

done identifying correct twist.

Algebraizing...
done.

Check for isomorphism...
done.
Curve found
Hyperelliptic Curve defined by y^2 = 1/16*x^6 - 1/8*x^5 - 3/16*x^4 + 7/8*x^3 - 9/8*x^2 + 1/2*x + 1/16 over Rational Field
Modular abelian variety 67C of dimension 2, level 67 and conductor 67^2 over Q
Periods computed
[8.1012452777175004857300643846356376908863131839261501293824689337224510681398561 4.0506226388587502428650321923178188454431565919630750646912344668612255340699281 - 0.23579743478063233909384790371479097387406154749387510460834979669570075199658367*I 13.541741099342098769803165110867002344760694564271499295858038932604333904415201 -2.7202479108122991420365503631156823269371906901726745832377849994409414181376724 + 3.6125848777139794978597550065384782529275676031952809707898052193017728512650271*I]
[2.6607494560929022016569636584042730370119318035808009629068989348405682318645165 1.330374728046451100828481829

0
Principal polarization found

GetCurve(
N: 69
)
>>         E, F := FrobeniusFormAlternating(Matrix(Integers(), pol)); E,F;
                                                  ^
Runtime error in 'Matrix': Bad argument types
Argument types given: RngInt, RngIntElt



In [13]:
GetCurve(69);

Modular abelian variety 69B of dimension 2, level 3*23 and conductor 3^2*23^2 over Q
Periods computed
[-2.5605218263977138469697439911660396594750745203271053217964217270607934809551565 - 3.7516732318770227341012754125212152113658788223800992864786761986261312575831885*I 1.4745168011697089859401175957298082724386986109506016637677174318041966273573082 8.4337583545844185794788592410160152061679691058948060400622104200865154327758077E-81 + 7.6324760648063567373526006693035917944671547068597920414244738495915379769947818*I -9.5445940563045546517598407695215041362662448735060156348959957495341768439822374 - 7.6324760648063567373526006693035917944671547068597920414244738495915379769947817*I]
[-5.5095554287371318188499791826256562043524717422283086493318565906691867356697732 + 3.8033250722979472417612953502256797600600376472199366738655247795618414423145509*I -2.4987255317287945247280151921962241362287284190814437924862861226285140197393722 -4.216879177292209289739429620508007603083984552947

# IsCorrectTwist

In [92]:
function IsCorrectTwist(C, f)
O := BaseRing(f);
    // L := LSeries(f: Embedding := 
    //  map< O -> ComplexField() | a :-> Conjugates(a)[1] >);
    M := ModularAbelianVariety(f);
    D := Discriminant(C);
    N := Level(f);
    for p in PrimesUpTo(1000) do
        if (Numerator(D) mod p eq 0) or (N mod p eq 0) then 
            print "skipping";
            print p;
            continue;
        end if;
        if EulerFactor(C,p) ne Reverse(FrobeniusPolynomial(M, p)) then
            print p;
            print EulerFactor(C,p);
            print Reverse(FrobeniusPolynomial(M, p));
            return false;
        end if;
    end for;
    return true;
end function;

Example to test this for 31

In [93]:
R<x> := PolynomialRing(Rationals()); C31 := HyperellipticCurve(R![-3, -2, 3, 4, -5], R![1, 0, 1, 1]);

In [94]:
IsCorrectTwist(C31, Newform("31A"));

skipping
31
true


In [97]:
ff := HyperellipticPolynomials(SimplifiedModel(C31));
R<x> := PolynomialRing(Rationals()); C31t4 := HyperellipticCurve(4*ff);
IsCorrectTwist(C31t4, Newform("31A"));

skipping
2
skipping
31
true


In [99]:
ff := HyperellipticPolynomials(SimplifiedModel(C31));
R<x> := PolynomialRing(Rationals()); C31t3 := HyperellipticCurve(3*ff);
IsCorrectTwist(C31t3, Newform("31A"));

skipping
2
skipping
3
5
25*$.1^4 + 10*$.1^3 + 11*$.1^2 + 2*$.1 + 1
25*$.1^4 - 10*$.1^3 + 11*$.1^2 - 2*$.1 + 1
false


In [100]:
ff := HyperellipticPolynomials(SimplifiedModel(C31));
R<x> := PolynomialRing(Rationals()); C31t6 := HyperellipticCurve(6*ff);
IsCorrectTwist(C31t6, Newform("31A"));

skipping
2
skipping
3
7
49*$.1^4 - 28*$.1^3 + 13*$.1^2 - 4*$.1 + 1
49*$.1^4 + 28*$.1^3 + 13*$.1^2 + 4*$.1 + 1
false
